/// PaymentRecoverySDK — Intelligent payment decline handling for TiendaNube / Yuno.
///
/// ## Quick Start
///
/// ```swift
/// import PaymentRecoverySDK
///
/// struct CheckoutView: View {
///     var body: some View {
///         PaymentRecoveryView(card: TestCard.all[0])
///     }
/// }
/// ```
///
/// ## Architecture
///
/// ```
/// PaymentResult → DeclineClassifier → RecoveryAction → PaymentRecoveryViewModel → PaymentRecoveryView
/// ```
///
/// - ``PaymentRecoveryView``: Drop-in SwiftUI view that handles the entire flow.
/// - ``DeclineClassifier``: Pure, testable function. Use standalone if you supply your own UI.
/// - ``SimulationService``: Async actor for demo / testing without a real payment backend.
/// - ``TestCard``: Pre-built set of 10 cards covering every scenario.
/// - ``AnalyticsDelegate``: Protocol for observing flow events.

import Foundation

// MARK: - Internal localization helper

/// Resolves a key from the SDK's own resource bundle.
/// Uses `Bundle.module` (generated by SPM) so the SDK's strings
/// do not conflict with the host application's bundles.
func localized(_ key: String) -> String {
    Bundle.module.localizedString(forKey: key, value: key, table: "Localizable")
}
